// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextLayer.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251028190458_AddDataConclusaoToChamado")]
    partial class AddDataConclusaoToChamado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextLayer.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.ToTable("Anexos", (string)null);
                });

            modelBuilder.Entity("NextLayer.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalistaId")
                        .HasColumnType("integer")
                        .HasColumnName("AnalistaId");

                    b.Property<bool>("AnalistaInteragiu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("AnalistaInteragiu");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("ClienteId");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAbertura");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataConclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<string>("NumeroChamado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NumeroChamado");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Prioridade");

                    b.Property<string>("RoleDesignada")
                        .HasColumnType("text")
                        .HasColumnName("RoleDesignada");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("AnalistaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Chamados", (string)null);
                });

            modelBuilder.Entity("NextLayer.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("NextLayer.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Funcionarios", (string)null);
                });

            modelBuilder.Entity("NextLayer.Models.FaqItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataCriacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataUltimaAtualizacao");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Pergunta");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Resposta");

                    b.HasKey("Id");

                    b.ToTable("FaqItens", (string)null);
                });

            modelBuilder.Entity("NextLayer.Models.MensagemChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteRemetenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FuncionarioRemetenteId")
                        .HasColumnType("integer");

                    b.Property<string>("RemetenteNome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("ClienteRemetenteId");

                    b.HasIndex("FuncionarioRemetenteId");

                    b.ToTable("MensagensChat", (string)null);
                });

            modelBuilder.Entity("NextLayer.Models.Anexo", b =>
                {
                    b.HasOne("NextLayer.Models.Chamado", "Chamado")
                        .WithMany("Anexos")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("NextLayer.Models.Chamado", b =>
                {
                    b.HasOne("NextLayer.Models.Employee", "Analista")
                        .WithMany()
                        .HasForeignKey("AnalistaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NextLayer.Models.Client", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analista");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("NextLayer.Models.MensagemChat", b =>
                {
                    b.HasOne("NextLayer.Models.Chamado", "Chamado")
                        .WithMany("Mensagens")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextLayer.Models.Client", "ClienteRemetente")
                        .WithMany()
                        .HasForeignKey("ClienteRemetenteId");

                    b.HasOne("NextLayer.Models.Employee", "FuncionarioRemetente")
                        .WithMany()
                        .HasForeignKey("FuncionarioRemetenteId");

                    b.Navigation("Chamado");

                    b.Navigation("ClienteRemetente");

                    b.Navigation("FuncionarioRemetente");
                });

            modelBuilder.Entity("NextLayer.Models.Chamado", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
